/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examtantra;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author tripa
 */
public class adminreeval extends javax.swing.JFrame {

    /**
     * Creates new form adminreeval
     */
    public adminreeval() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lques = new javax.swing.JTextArea();
        lo1 = new javax.swing.JRadioButton();
        lo2 = new javax.swing.JRadioButton();
        lo3 = new javax.swing.JRadioButton();
        lo4 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        exp = new javax.swing.JTextArea();
        update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--" }));
        cb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMouseClicked(evt);
            }
        });
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });

        jLabel1.setText("TESTID");

        jLabel2.setText("QNO.");

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT--" }));
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        lques.setEditable(false);
        lques.setColumns(20);
        lques.setRows(5);
        jScrollPane1.setViewportView(lques);

        buttonGroup1.add(lo1);
        lo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lo1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(lo2);
        lo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lo2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(lo3);
        lo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lo3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(lo4);
        lo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lo4ActionPerformed(evt);
            }
        });

        exp.setEditable(false);
        exp.setColumns(20);
        exp.setRows(5);
        jScrollPane2.setViewportView(exp);

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("EXPECTED ANSWER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update)
                    .addComponent(lo2)
                    .addComponent(lo3)
                    .addComponent(lo4)
                    .addComponent(lo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lo1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lo2)
                        .addGap(18, 18, 18)
                        .addComponent(lo3)
                        .addGap(18, 18, 18)
                        .addComponent(lo4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update)
                    .addComponent(jButton2))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lo1ActionPerformed
update.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lo1ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
if(cb1.getSelectedIndex()==0)
{
     lques.setText("");
            lo1.setText("");
            lo2.setText("");
            lo3.setText("");
            lo4.setText("");
            exp.setText("");
}else
{
        try{
    exp.setText("");
Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
            String str="Select * from questionbank where testid='"+cb.getSelectedItem()+"' and qno = "+cb1.getSelectedItem()+";";
            ResultSet rs1=stmt.executeQuery(str);
              if(rs1.next())
              {
                  String question=rs1.getString("question");
                  String opt1=rs1.getString("option1");
                  String opt2=rs1.getString("option2");
                  String opt3=rs1.getString("option3");
                  String opt4=rs1.getString("option4");           
                  lques.setText(""+question);
                  lo1.setText(""+opt1);
                  lo2.setText(""+opt2);
                  lo3.setText(""+opt3);
                  lo4.setText(""+opt4);
                  
              }
              String str1="Select distinct expans from reeval where testid='"+cb.getSelectedItem()+"' and qno = "+cb1.getSelectedItem()+";";
              ResultSet rs2=stmt.executeQuery(str1);
              while (rs2.next())
              {
                  String a = rs2.getString("expans");
                  exp.append(""+a+"\n");
              }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}}  // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
update.setEnabled(false);
        try{
    Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
            String t="select distinct testid from reeval";
             ResultSet rs=stmt.executeQuery(t);
             while(rs.next())
             {
                 
                     String s=rs.getString("testid");
                     cb.addItem(s);
             }               
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
     if(cb.getSelectedIndex()==0)
     {
          cb1.removeAllItems();
            lques.setText("");
            lo1.setText("");
            lo2.setText("");
            lo3.setText("");
            lo4.setText("");
            cb1.addItem("--SELECT--");
         cb1.setSelectedIndex(0);
     }  else
            {     
            
        try{     
           
            
            cb1.removeAllItems();
            lques.setText("");
            lo1.setText("");
            lo2.setText("");
            lo3.setText("");
            lo4.setText("");
            cb1.addItem("--SELECT--");
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
            String t="select distinct qno from reeval where testid = '"+cb.getSelectedItem()+"';" ;
            ResultSet rs=stmt.executeQuery(t);
            
 

            
            
            while(rs.next())
             {
                 
                     String s=rs.getString("qno");
                     cb1.addItem(s);
                 }
}
        
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}  }      // TODO add your handling code here:
    }//GEN-LAST:event_cbActionPerformed

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ItemStateChanged

    private void cbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMouseClicked

                   // TODO add your handling code here:
    }//GEN-LAST:event_cbMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
adminmenu a=new adminmenu();
a.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
if(lo1.isSelected()==true||lo2.isSelected()==true||lo3.isSelected()==true||lo4.isSelected()==true)
{
    update.setEnabled(true);
        String ans="";
if(lo1.isSelected()==true)
{
    ans=lo1.getText();
}else if(lo2.isSelected()==true)
{
    ans=lo2.getText();
}else if(lo3.isSelected()==true)
{
    ans=lo3.getText();
}else if(lo4.isSelected()==true)
{
    ans=lo4.getText();
} 

        try
{ 
    //get all students of particular testid
    int n=0;
    Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
            String coun="select count(distinct(studid)) as count from studans where tid='"+cb.getSelectedItem()+"';";
            ResultSet rs20=stmt.executeQuery(coun);
            if(rs20.next())
            {
                int m=rs20.getInt("count");
                n=m; //total students given that particular test
                
            }
            
            String ids="select distinct studid from studans where tid='"+cb.getSelectedItem()+"';";
            ResultSet rs9=stmt.executeQuery(ids);
            String[] ns = new String[n];
            int i=0;
            while(rs9.next())
            {
                String s=rs9.getString("studid");
                ns[i]=s;         //ids of all student given that particulae test
                i++;
            }
             
            //updated ans
            String str="Update questionbank set answer='"+ans+"' where testid='"+cb.getSelectedItem()+"' and qno="+cb1.getSelectedItem()+";";
            stmt.executeUpdate(str);
           
            
            //update studentmarks for all
            for(int j=0;j<n;j++)
            {
                
                //totalquestionfrom particular test
                int t=0;
                String totalques="Select ques from testinfo where testcode='"+cb.getSelectedItem()+"';";
                ResultSet rs69=stmt.executeQuery(totalques);
                if(rs69.next())
                {
                    int h=rs69.getInt("ques");
                    t=h;
                }
                 
                 
                String studa="Select * from studans where tid='"+cb.getSelectedItem()+"' and studid='"+ns[j]+"';";
                ResultSet rs=stmt.executeQuery(studa);            
                String[] sans=new String[t];
                int l=0;
                while(rs.next())
                {
                             
                    String selans=rs.getString("selectedans");
                    sans[l]=selans;
                    l++;
               
                }
                
                
                
                String[] cans = new String[t];
            String s3="Select answer from questionbank where testid='"+cb.getSelectedItem()+"';";
            ResultSet rs3=stmt.executeQuery(s3);
            int count2=0;
            while(rs3.next())
            {
                String ss=rs3.getString("answer");
                cans[count2]=ss;
                count2++;
               
            }
               
            int wro=0,cor=0,lef=0;
            for(int y=0;y<t;y++)
            {
                if(sans[y].equals(cans[y]))
                {
                    cor++;
                }
            }
            for(int y=0;y<t;y++)
            {
                if(!sans[y].equals(cans[y])&&!sans[y].equals("null"))
                {
                   
                    wro++;
                }
            }
            lef=t-cor-wro;
            int totalmark=(cor*4)+(wro*-1)+(lef*0);
            
            //update marks
            String query1="Update student_marks set correct="+cor+" where testid='"+cb.getSelectedItem()+"' and studid='"+ns[j]+"'; ";
            stmt.executeUpdate(query1);
            
            String query2="Update student_marks set wrong="+wro+" where testid='"+cb.getSelectedItem()+"' and studid='"+ns[j]+"'; ";
            stmt.executeUpdate(query2);
            
            String query3="Update student_marks set lefts="+lef+" where testid='"+cb.getSelectedItem()+"' and studid='"+ns[j]+"'; ";
            stmt.executeUpdate(query3);
            
            String query4="Update student_marks set marks="+totalmark+" where testid='"+cb.getSelectedItem()+"' and studid='"+ns[j]+"'; ";
            stmt.executeUpdate(query4);
            
            }
            JOptionPane.showMessageDialog(null,"UPDATED");
            lo1.setText("");
             lo2.setText("");
              lo3.setText("");
               lo4.setText("");
               buttonGroup1.clearSelection();
               lques.setText("");
               exp.setText(""); 
               if(cb1.getSelectedIndex()!=0)
               {
                    
                    String del="delete from reeval where testid='"+cb.getSelectedItem()+"' and qno='"+cb1.getSelectedItem()+"';";
                    
                            cb1.removeItem(cb1.getSelectedItem());
                            int a=cb1.getItemCount();
                            if(a==1)
                            {
                                cb.removeItem(cb.getSelectedItem());
                            }
                                stmt.executeUpdate(del);
               }
               update.setEnabled(false);
              
               
            
    
}catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}
}
    }//GEN-LAST:event_updateActionPerformed

    private void lo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lo2ActionPerformed
   update.setEnabled(true);       // TODO add your handling code here:
    }//GEN-LAST:event_lo2ActionPerformed

    private void lo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lo3ActionPerformed
update.setEnabled(true);          // TODO add your handling code here:
    }//GEN-LAST:event_lo3ActionPerformed

    private void lo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lo4ActionPerformed
update.setEnabled(true);          // TODO add your handling code here:
    }//GEN-LAST:event_lo4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminreeval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminreeval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminreeval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminreeval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminreeval().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JTextArea exp;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton lo1;
    private javax.swing.JRadioButton lo2;
    private javax.swing.JRadioButton lo3;
    private javax.swing.JRadioButton lo4;
    private javax.swing.JTextArea lques;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
