/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examtantra;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Subhra CHOUDHURY
 */
public class admstudentinfo extends javax.swing.JFrame {

    /**
     * Creates new form admstudentinfo
     */
    public admstudentinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbroll = new javax.swing.JComboBox<>();
        txtclass = new javax.swing.JTextField();
        cbcode = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tsub = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        marksscored = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("NAME");

        jLabel3.setText("CLASS");

        jLabel2.setText("STUDENT ROLL NO");

        cbroll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT ROLL NO.--" }));
        cbroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrollActionPerformed(evt);
            }
        });

        cbcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECT TEST CODE--" }));
        cbcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcodeActionPerformed(evt);
            }
        });

        jLabel4.setText("TEST");

        jLabel5.setText("SUBJECT");

        jLabel6.setText("TOTAL MARKS");

        jLabel7.setText("MARKS SCORED");

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("STUDENT REPORT");

        delete.setText("DELETE STUDENT");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(marksscored, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tsub, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbroll, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtclass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalm)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbcode, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jButton1)
                        .addGap(65, 65, 65)
                        .addComponent(delete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel8)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(marksscored, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(delete))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
adminmenu a=new adminmenu();
a.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
delete.setVisible(false);
        try
{
     Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
            String t="select roll from studinfo";
             ResultSet rs=stmt.executeQuery(t);
             while(rs.next())
             {
                 
                     String s=rs.getString("roll");
                     cbroll.addItem(s);
                 }
             String q="select testcode from testinfo";
             ResultSet rs1=stmt.executeQuery(q);
             while(rs1.next())
             {
                 
                     String s=rs1.getString("testcode");
                     cbcode.addItem(s);
                 }
             
    
}catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cbrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrollActionPerformed
tsub.setText("");
    marksscored.setText("");
    totalm.setText("");
    cbcode.setSelectedIndex(0);
        if(cbroll.getSelectedIndex()==0)
{
    name.setText("");
    txtclass.setText("");
    tsub.setText("");
    marksscored.setText("");
    totalm.setText("");
    cbcode.setSelectedIndex(0);
}
else
{
    delete.setVisible(true);
    try{
         Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
            String info="Select name,class from studinfo where roll='"+cbroll.getSelectedItem()+"';";
            ResultSet rs=stmt.executeQuery(info);
            if(rs.next())
            {
                String n=rs.getString("name");
                String c=rs.getString("class");
                name.setText(""+n);
                txtclass.setText(""+c);
            }
        
        
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,e);
    }
}// TODO add your handling code here:
    }//GEN-LAST:event_cbrollActionPerformed

    private void cbcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcodeActionPerformed
if(cbcode.getSelectedIndex()==0)
{
    tsub.setText("");
    marksscored.setText("");
    totalm.setText("");
}else{
        try{
     Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
            String str="select * From testinfo where testcode='"+ cbcode.getSelectedItem()+"';";
       ResultSet rs=stmt.executeQuery(str);
       if(rs.next())
       {
           String sub=rs.getString("subject");
           tsub.setText(""+sub);
       }
       String tm="Select ques from testinfo where testcode='"+ cbcode.getSelectedItem()+"';";
       ResultSet rs2=stmt.executeQuery(tm);
       if(rs2.next())
       {
           int q=rs2.getInt("ques");
           totalm.setText(""+q*4);
       }
       String md="Select marks from student_marks where testid='"+cbcode.getSelectedItem()+"' and studid='"+cbroll.getSelectedItem()+"';";
       ResultSet rs5=stmt.executeQuery(md);
       if(rs5.next())
       {
           int mk=rs5.getInt("marks");
           marksscored.setText(""+mk);
       }else
            {
                JOptionPane.showMessageDialog(null,"TEST NOT ATTEMPTED YET");
                marksscored.setText("");
    totalm.setText("");
    cbcode.setSelectedIndex(0);
    tsub.setText("");
                
            }
       
      
    

    
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
} 
}        // TODO add your handling code here:
    }//GEN-LAST:event_cbcodeActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
if(cbroll.getSelectedIndex()!=0)
{
    delete.setVisible(true);
        int resp=JOptionPane.showConfirmDialog(this, "DO YOU WANT TO REMOVE THIS STUDENT FROM DATABASE? ");

        if(resp==JOptionPane.YES_OPTION)
        {
            try
            {
                Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
            String s1="delete from studinfo where roll="+cbroll.getSelectedItem()+";";
             String s2="delete from reeval where studid="+cbroll.getSelectedItem()+";";
              String s3="delete from student_marks where studid="+cbroll.getSelectedItem()+";";
              String s4="delete from studans where studid="+cbroll.getSelectedItem()+";";
              
            
                 stmt.executeUpdate(s1);
                 stmt.executeUpdate(s2);
                 stmt.executeUpdate(s3);
                 stmt.executeUpdate(s4);
            
            JOptionPane.showMessageDialog(null,"DELETED");
            adminmenu a=new adminmenu();
            a.setVisible(true);
            this.dispose();
            
           
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
                
            }
        }   
}
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admstudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admstudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admstudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admstudentinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admstudentinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbcode;
    private javax.swing.JComboBox<String> cbroll;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField marksscored;
    private javax.swing.JTextField name;
    private javax.swing.JTextField totalm;
    private javax.swing.JTextField tsub;
    private javax.swing.JTextField txtclass;
    // End of variables declaration//GEN-END:variables
}
