/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examtantra;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author Subhra CHOUDHURY
 */
public class answersheetview extends javax.swing.JFrame {
    public String x1;
    public String x2;
    public int r;
    public int qr;
    /**
     * Creates new form answersheetview
     */
    public answersheetview(String xa,String xb) {
        initComponents();
        x1=xa;
        x2=xb;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    answersheetview() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        asid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        atid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        correct = new javax.swing.JTextField();
        wrong = new javax.swing.JTextField();
        left = new javax.swing.JTextField();
        gm = new javax.swing.JButton();
        reeval = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        marks = new javax.swing.JTextField();
        qcb = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        eo1 = new javax.swing.JRadioButton();
        eo2 = new javax.swing.JRadioButton();
        eo3 = new javax.swing.JRadioButton();
        eo4 = new javax.swing.JRadioButton();
        lbl = new javax.swing.JLabel();
        btns = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QUESTION NUMBER", "CORRECT ANSWER", "YOUR ANSWER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                tableComponentRemoved(evt);
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        asid.setEditable(false);

        jLabel1.setText("STUDENT ID");

        jLabel2.setText("TEST ID");

        atid.setEditable(false);

        jLabel3.setText("TOTAL CORRECT");

        jLabel4.setText("TOTAL WRONG");

        jLabel5.setText("TOTAL LEFT");

        correct.setEditable(false);

        wrong.setEditable(false);

        left.setEditable(false);

        gm.setText("GO TO STUDENT MENU");
        gm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmActionPerformed(evt);
            }
        });

        reeval.setText("APPLY FOR REEVAL");
        reeval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reevalActionPerformed(evt);
            }
        });

        jLabel6.setText("TOTAL MARKS");

        marks.setEditable(false);

        qcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select a q_no. to view--" }));
        qcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qcbActionPerformed(evt);
            }
        });

        submit.setText("SUBMIT & EXIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel7.setText("QUESTION VIEW");

        buttonGroup1.add(eo1);
        eo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eo1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(eo2);
        eo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eo2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(eo3);
        eo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eo3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(eo4);

        lbl.setText("EXPECTED ANSWER");

        btns.setText("SUBMIT AND NEXT");
        btns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(26, 26, 26)
                            .addComponent(correct, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(wrong, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(marks, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(atid, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(asid, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reeval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btns)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(eo2)
                                        .addComponent(eo1)
                                        .addComponent(eo3)
                                        .addComponent(eo4)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(qcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eo4)
                .addGap(18, 18, 18)
                .addComponent(btns)
                .addGap(48, 48, 48)
                .addComponent(gm)
                .addGap(31, 31, 31)
                .addComponent(reeval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(atid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(correct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(wrong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reevalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reevalActionPerformed
JOptionPane.showMessageDialog(null,"PLEASE SELECT THE QUESTION ROW FROM TABLE TO BE APPLIED FOR REEVALUATION");
        gm.setEnabled(false);
 reeval.setEnabled(false);
 submit.setVisible(true);
 submit.setEnabled(true);
 table.setEnabled(true);
 lbl.setVisible(true);
eo1.setVisible(true);
eo2.setVisible(true);
eo3.setVisible(true);
eo4.setVisible(true);


 
 
        
    }//GEN-LAST:event_reevalActionPerformed

    private void gmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmActionPerformed
try
{
     Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
            String sv="Insert into student_marks values('"+atid.getText()+"','"+asid.getText()+"',"+correct.getText()+","+wrong.getText()+","+left.getText()+","+marks.getText()+");";
            stmt.executeUpdate(sv);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}
       
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_gmActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
lbl.setVisible(false);
eo1.setVisible(false);
eo2.setVisible(false);
eo3.setVisible(false);
eo4.setVisible(false);
btns.setEnabled(false);
btns.setVisible(false);
eo1.setEnabled(false);
eo2.setEnabled(false);
eo3.setEnabled(false);
eo4.setEnabled(false);

 atid.setText(""+x1);
 asid.setText(""+x2);
 submit.setVisible(false);
 submit.setEnabled(false);
 try
 {
     int qu=0;
     DefaultTableModel my_model=(DefaultTableModel) table.getModel();
      table.setRowSelectionAllowed(false);
      table.setEnabled(false);
     Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
            String s1="Select count(sqno) from studans where tid='"+x1+"' and studid='"+x2+"';";
             ResultSet rs=stmt.executeQuery(s1);
             if(rs.next())
             {
              int q=rs.getInt("count(sqno)");
              qu=q;
             }
            int count=1;
            int[] qn = new int[qu]; 
            for(int i=0;i<qu;i++)
            {
                qn[i]=count;
                    
                
                count++;
            }
           /* String sss="Select qno from questionbank where testid='"+x1+"';";
            ResultSet rs4=stmt.executeQuery(sss);
            while(rs4.next())
            {
                int q=rs4.getInt("qno");
                
                qcb.addItem();
            }*/
           for(int i=0;i<qu;i++)
           {
               int a=qn[i];
               String b=String.valueOf(a);
               qcb.addItem(b);              
               
           }
            
           
           
            String[] sans = new String[qu];
            String s2="Select selectedans from studans where tid='"+x1+"' and studid='"+x2+"';";
            ResultSet rs2=stmt.executeQuery(s2);
            int count1=0;
            while(rs2.next())
            {
                String ss=rs2.getString("selectedans");
                sans[count1]=ss;
                count1++;
                
            }
            String[] cans = new String[qu];
            String s3="Select answer from questionbank where testid='"+x1+"';";
            ResultSet rs3=stmt.executeQuery(s3);
            int count2=0;
            while(rs3.next())
            {
                String ss=rs3.getString("answer");
                cans[count2]=ss;
                count2++;
               
            }
            for(int i=0;i<qu;i++)
            {
                Object[] row={qn[i],cans[i],sans[i]};
                my_model.addRow(row);
            }
            
            int wro=0,cor=0,lef=0;
            for(int i=0;i<qu;i++)
            {
                if(sans[i].equals(cans[i]))
                {
                    cor++;
                }
            }
            for(int i=0;i<qu;i++)
            {
                if(!sans[i].equals(cans[i])&&!sans[i].equals("null"))
                {
                   
                    wro++;
                }
            }
            lef=qu-cor-wro;
            
            correct.setText(""+cor);
            wrong.setText(""+wro);
            left.setText(""+lef);
            int totalmark=(cor*4)+(wro*-1)+(lef*0);
            marks.setText(""+totalmark);
                        
 }
 catch(Exception e)
 {
     JOptionPane.showMessageDialog(null,e);
     
 }
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void qcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qcbActionPerformed
if(qcb.getSelectedIndex()==0)
{
    
}else
{
     try{
     Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
            String str="select question From questionbank where qno="+ qcb.getSelectedItem()+" and testid='"+x1+"';";
       ResultSet rs=stmt.executeQuery(str);
       if(rs.next())
       {
           String sub=rs.getString("question");
           JOptionPane.showMessageDialog(null,sub);
       }
       
    

    
}
catch(Exception e)
{
}
}// TODO add your handling code here:
    }//GEN-LAST:event_qcbActionPerformed

    private void tableComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tableComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tableComponentRemoved

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
eo1.setEnabled(true);
eo2.setEnabled(true);
eo3.setEnabled(true);
eo4.setEnabled(true);
submit.setEnabled(false);

        DefaultTableModel model=(DefaultTableModel) table.getModel();
if(reeval.isEnabled()==(false))
{
  table.setRowSelectionAllowed(true);
}
 else
{
    table.setRowSelectionAllowed(false);
}
        try
        {
            int qu=0;
             Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();/*
            String s1="Select count(sqno) from studans where tid='"+x1+"' and studid='"+x2+"';";
             ResultSet rs=stmt.executeQuery(s1);
             if(rs.next())
             {
              int q=rs.getInt("count(sqno)");
              qu=q;
             }*/
             
            
              r=table.getSelectedRow();
              String value = table.getModel().getValueAt(r, 0).toString();
              qr=Integer.parseInt(value);
              
              String qwe="Select * from questionbank where testid='"+x1+"' and qno="+qr+";";
            ResultSet rs11=stmt.executeQuery(qwe);
              if(rs11.next())
              {
         
                  
                  String opt1=rs11.getString("option1");
                  String opt2=rs11.getString("option2");
                  String opt3=rs11.getString("option3");
                  String opt4=rs11.getString("option4");
                  
                 
                  eo1.setText(""+opt1);
                  eo2.setText(""+opt2);
                  eo3.setText(""+opt3);
                  eo4.setText(""+opt4);
                  JOptionPane.showMessageDialog(null,"PLEASE SELECT EXPECTED ANSWER");
                  btns.setVisible(true);
btns.setEnabled(true);
                  
              }
            
             
              
             
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
try
{
     Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
            String sv="Insert into student_marks values('"+atid.getText()+"','"+asid.getText()+"',"+correct.getText()+","+wrong.getText()+","+left.getText()+","+marks.getText()+");";
            stmt.executeUpdate(sv);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e);
}
        
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void eo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eo2ActionPerformed

    private void eo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eo1ActionPerformed

    private void eo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eo3ActionPerformed

    private void btnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsActionPerformed
try{
    DefaultTableModel model=(DefaultTableModel) table.getModel();
    Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/examtantra","root","1192002");
            Statement stmt=con.createStatement();
    
        
            
            
            
            String expans="";
            if(eo1.isSelected()==true)
            {
                expans=eo1.getText();
            } else if(eo2.isSelected()==true)
            {
                expans=eo2.getText();
            } else if(eo3.isSelected()==true)
            {
                expans=eo3.getText();
            } else if(eo4.isSelected()==true)
            {
                expans=eo4.getText();
            }
            
            String str="Insert into reeval values('"+atid.getText()+"','"+asid.getText()+"',"+qr+",'"+expans+"');";
            if(expans.equals(""))
            { 
                 JOptionPane.showMessageDialog(null,"PLEASE SELECT EXPECTED ANSWER");
            }
            else
            {
            stmt.executeUpdate(str);
            model.removeRow(r);
            JOptionPane.showMessageDialog(null,"GIVEN FOR REEVAL");
            submit.setEnabled(true);
            eo1.setEnabled(false);
eo2.setEnabled(false);
eo3.setEnabled(false);
eo4.setEnabled(false);
buttonGroup1.clearSelection();
eo1.setText("");
eo2.setText("");
eo3.setText("");
eo4.setText("");



btns.setVisible(false);
btns.setEnabled(false);
            }
            
           
              
        
             
}catch(Exception e)
{
}// TODO add your handling code here:
    }//GEN-LAST:event_btnsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(answersheetview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(answersheetview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(answersheetview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(answersheetview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new answersheetview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asid;
    private javax.swing.JTextField atid;
    private javax.swing.JButton btns;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField correct;
    private javax.swing.JRadioButton eo1;
    private javax.swing.JRadioButton eo2;
    private javax.swing.JRadioButton eo3;
    private javax.swing.JRadioButton eo4;
    private javax.swing.JButton gm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl;
    private javax.swing.JTextField left;
    private javax.swing.JTextField marks;
    private javax.swing.JComboBox<String> qcb;
    private javax.swing.JButton reeval;
    private javax.swing.JButton submit;
    private javax.swing.JTable table;
    private javax.swing.JTextField wrong;
    // End of variables declaration//GEN-END:variables
}
